#!/bin/bash -e

## https://serverfault.com/a/580630/120096
iptables -I INPUT -p tcp --dport 443 --syn -j DROP
sleep 1
service haproxy restart
iptables -D INPUT -p tcp --dport 443 --syn -j DROP

## you can use other logics here too
